version: '3'

services:
  addmodule:
    image: addmodule
    build:
      context: ./addmodule
      dockerfile: Dockerfile
    network_mode: "host"
  
  submodule:
    image: submodule
    build:
      context: ./submodule
      dockerfile: Dockerfile
    network_mode: "host"

  divmodule:
    image: divmodule
    build:
      context: ./divmodule
      dockerfile: Dockerfile
    network_mode: "host" 

  mulmodule:
    image: mulmodule
    build:
      context: ./mulmodule
      dockerfile: Dockerfile
    network_mode: "host"

  mainmodule:
    image : mainmodule
    build:
      context: ./mainmodule
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - addmodule
      - submodule
      - divmodule
      - mulmodule